### PR TITLE
Custom url encoding

### PR DESCRIPTION
**Pull request by nathanstitt**
I'm working on a project that has complex URL encoding requirements.

Instead of over-riding the existing patches to String, I've modified the code to use an URLEncoder class that can be swapped out for a differing implementation.

I'd be glad to re-work if you'd like a differing implementation.
Thanks!

### CODE REVIEW

**Comment by tkadauke** [comment]
This looks amazing and I'd love to merge this pull request, but unfortunately your changes do not conform to the coding style. For example, you put a space after an opening parenthesis, or an empty line after a module declaration and before the "end" statement. Could you please correct the coding style of your changes? Thanks for the pull request!

**Comment by nathanstitt** [comment]
Sure, not a problem at all.  I _think_ I've corrected all the spaces after opening parentheses and removed the lines from url_encoder.

If you spot any I've missed please let me know

**Comment by tkadauke** [comment]
Thanks for the fixes. You caught most of them, but not quite all :-) Please see https://github.com/tkadauke/motion-resource/pull/12/files (Files changed tab on the top) and look at all the green lines.

**Comment by nathanstitt** [comment]
Think perhaps I've got 'em all ?

**Comment by tkadauke** [comment]
All but one, but I fixed it :-)

**Pull request merged**
